# jar匹配类型、jar名字和版本的对应关系,坐标必须是数字 x.y.z

#
base:
  wardir: "d:\\gaga-dev"
  exts:
    - ".war"
    - ".ear"
    - ".jar"

# 相等匹配
eq:
  - xz:9.9.9
  - xy:9.9.9
# 大于等于匹配
le:
  - fastjson:1.2.87
  - zookeeper:3.4.14
